name: Deploy Grid Event Simulator Azure Static Web Apps

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      #- 'grid-event-simulator/backend_app/**'
      - 'grid-event-simulator/website/**'
      - '.github/workflows/grid-event-simulator.actions.yaml'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      
      #- name: Setup .NET for API
      #  uses: actions/setup-dotnet@v4
      #  with:
      #    dotnet-version: '8.0.x'
      
      #- name: Restore and build API
      #  run: |
      #    dotnet restore
      #    dotnet build --configuration Release
      #  working-directory: demand-forecast/backend_app

      #- name: Publish API
      #  run: |
      #    dotnet publish --configuration Release --output ./publish
      #    cd ./publish
      #    zip -r ../deploy.zip .
      #  working-directory: demand-forecast/backend_app

      #- name: Azure Login
      #  uses: azure/login@v1
      #  with:
      #    creds: ${{ secrets.AZURE_CREDENTIALS }}

      #- name: Deploy to Azure Functions
      #  uses: Azure/functions-action@v1
      #  with:
      #    app-name: 'func-multiagent-eus2-mx01'
      #    package: 'demand-forecast/backend_app/deploy.zip'

      - name: Build And Deploy Frontend
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ORCH_MULTI_AGENT_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: grid-event-simulator/website
          output_location: grid-event-simulator/website/dist