
on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: xximjasonxx/actions-workflow-repo/reusable-flow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      personal_access_token: ${{ secrets.token }}